### ISSUE TITLE
Add Project

### ISSUE THREAD

**Issue by zeel-codder** [Mitali-laroia/Circle-Crework-Backend#11]
create API which allows users to add projects.

**Comment by Mitali-laroia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [✋🏿 Week-4 Goals](https://trello.com/c/1ixcPyYY/2-%E2%9C%8B%F0%9F%8F%BF-week-4-goals)

**Comment by Mitali-laroia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Project Add](https://trello.com/c/LU3awMzI/1-project-add)

**Comment by Mitali-laroia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Post request for adding a project](https://trello.com/c/fKVKEQcw/2-post-request-for-adding-a-project)
