### ISSUE TITLE
Project Join 

### ISSUE THREAD

**Issue by Mitali-laroia** [Mitali-laroia/Circle-Crework-Backend#25]
Implementing the feature of a joining a project.

**Comment by zeel-codder** [comment]
**so, we can divide this into two-part,** 
1. any user can request to join the project
2. the creator of the project can add the user as per the request

both of them are related to project updates ( on top)
so, we require two APIs for this function.

**Some point to be done**
1. when your user is making a request to project join be make sure in creator notification we have notification as "some peer want to join your this project" (any other message also fine)
2. same when the creator adds the user to the team in user notification we can add a message that "you are now part of this project:"

**Comment by Mitali-laroia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Member Add Request](https://trello.com/c/k1KhcQxp/5-member-add-request)
