### ISSUE TITLE
Notification Workflow

### ISSUE THREAD

**Issue by zeel-codder** [Mitali-laroia/Circle-Crework-Backend#26]
Right now we are going to make a simple notification system when a user opens the popup/ page of notification on the client side we have a request to make all notifications as reading (change bool).

another thing we can add a notification from the backend while the user does signup/sign, add a project, join another project, etc. but this is for further right now just to make sure to add notification for the #25 issue.

2 APIs
1. get all notifications of the user
2. make all notifications as read

**Comment by Mitali-laroia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Notification workflow](https://trello.com/c/dFjEfyEM/6-notification-workflow)
